const carsInfo = 1 ? {
    1: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Плейсхолдър дас дас дас д асдаскйдкоас йдаскл йдкласйдклсайд класйдклсайдклс айд с дусгхд хигсдхйагайсхдфгсдх йагфсдх йгф сдхйагфй сдгахйфг кхйдсгфхй сдгйахф гхйкдс гйкфхсдагкфхйасдгхйкфгсдк фгксдгфкйасдхг фйксдх фгсдхй гфсдхйа гфхйасдг ',
        history: 'дйкласд йклас йдсайд асйлкд йасклд йлкас йдкласйд класйд класд йкласйд класйд класйд класй дкласйд класйд клсайд клхафйклсгфйлхдфг йлхасфгх йкасдгф кхйасдфгх йкасд фгхйкдасг фйкасдхгф йасдх й сдфх йксдфх йклдфх йкласхйклсдф хйкдф хйклдф хлдф йксхй',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    2: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
} : {
    1: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis corporis repellendus illo veniam aliquid repellat doloribus non, et facilis officiis, rerum facere fuga. Repellendus at, quos repellat harum laboriosam aliquid!',
        history: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis corporis repellendus illo veniam aliquid repellat doloribus non, et facilis officiis, rerum facere fuga. Repellendus at, quos repellat harum laboriosam aliquid!',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    2: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    3: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    4: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    5: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    6: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    7: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    8: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    9: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    10: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    11: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 23,
    },
    12: {
        brand: 'Cadillac',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    13: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    14: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    15: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 25,
    },
    16: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 22,
    },
    17: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    18: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 22,
    },
    19: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    20: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    21: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 22,
    },
    22: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    23: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    24: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 26,
    },
    25: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    26: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    27: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    28: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 26,
    },
    29: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    30: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 25,
    },
    31: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    32: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    33: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 26,
    },
    34: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24
    },
    35: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    36: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 25,
    },
    37: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    38: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    39: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    40: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    41: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    42: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    43: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    44: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    45: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    46: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    47: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    48: {
        brand: 'Mercedes',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    49: {
        brand: 'Buick',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
    50: {
        brand: 'Cadillac',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 27,
    },
    51: {
        brand: 'Cadillac',
        model: 'Placeholder model',
        yearMade: 'Placeholder yearMade',
        outerColor: 'Placeholder outerColor',
        innerColor: 'Placeholder innerColor',
        engine: 'Placeholder engine',
        kilometers: 'Placeholder kilometers',
        status: 'Placeholder status',
        crashes: 'Placeholder crashes',
        extras: 'Placeholder extras',
        history: 'Placeholder history',
        price: 'Placeholder price',
        imagesCount: 24,
    },
}

export default carsInfo