const categoriesInfo = [
    {
        id: 1,
        name: 'Mercedes',
        title: '',
        sub: '',
    },
    {
        id: 2,
        name: 'Mercedes',
        title: '',
        sub: '',
    },
    {
        id: 3,
        name: 'Mercedes',
        title: '',
        sub: '',
    },
    {
        id: 4,
        name: 'Mercedes',
        title: '',
        sub: '',
    },
    {
        id: 5,
        name: 'Mercedes',
        title: '',
        sub: '',
    },
    {
        id: 6,
        name: 'Mercedes',
        title: '',
        sub: '',
    },
    {
        id: 7,
        name: 'Mercedes',
        title: '',
        sub: '',
    },
    {
        id: 8,
        name: 'Mercedes',
        title: '',
        sub: '',
    },
    {
        id: 9,
        name: 'Mercedes',
        title: '',
        sub: '',
    },
    {
        id: 10,
        name: 'Mercedes',
        title: '',
        sub: '',
    },
    {
        id: 11,
        name: 'Mercedes',
        title: '',
        sub: '',
    },
    {
        id: 12,
        name: 'Cadillac',
        title: '',
        sub: '',
    },
    {
        id: 13,
        name: 'Cadillac',
        title: '',
        sub: '',
    },
    {
        id: 14,
        name: 'Cadillac',
        title: '',
        sub: '',
    },
    {
        id: 15,
        name: 'Cadillac',
        title: '',
        sub: '',
    },
    {
        id: 16,
        name: 'Cadillac',
        title: '',
        sub: '',
    },
    {
        id: 17,
        name: 'Cadillac',
        title: '',
        sub: '',
    },
    {
        id: 18,
        name: 'Buick',
        title: '',
        sub: '',
    },
    {
        id: 19,
        name: 'Cadillac',
        title: '',
        sub: '',
    },
    {
        id: 20,
        name: 'Mercedes',
        title: '',
        sub: '',
    },
    {
        id: 21,
        name: 'Cadillac',
        title: '',
        sub: '',
    },
    {
        id: 22,
        name: 'Cadillac',
        title: '',
        sub: '',
    },
    {
        id: 23,
        name: 'Cadillac',
        title: '',
        sub: '',
    },
    {
        id: 24,
        name: 'Others',
        title: '',
        sub: '',
    },
    {
        id: 25,
        name: 'Buick',
        title: '',
        sub: '',
    },
    {
        id: 26,
        name: 'Mercedes',
        title: '',
        sub: '',
    },
    {
        id: 27,
        name: 'Cadillac',
        title: '',
        sub: '',
    },
    {
        id: 28,
        name: 'Cadillac',
        title: '',
        sub: '',
    },
    {
        id: 29,
        name: 'Others',
        title: '',
        sub: '',
    },
    {
        id: 30,
        name: 'Others',
        title: '',
        sub: '',
    },
    {
        id: 31,
        name: 'Others',
        title: '',
        sub: '',
    },
    {
        id: 32,
        name: 'Others',
        title: '',
        sub: '',
    },
    {
        id: 33,
        name: 'Cadillac',
        title: '',
        sub: '',
    },
    {
        id: 34,
        name: 'Buick',
        title: '',
        sub: '',
    },
    {
        id: 35,
        name: 'Buick',
        title: '',
        sub: '',
    },
    {
        id: 36,
        name: 'Others',
        title: '',
        sub: '',
    },
    {
        id: 37,
        name: 'Mercedes',
        title: '',
        sub: '',
    },
    {
        id: 38,
        name: 'Cadillac',
        title: '',
        sub: '',
    },
    {
        id: 39,
        name: 'Buick',
        title: '',
        sub: '',
    },
    {
        id: 40,
        name: 'Cadillac',
        title: '',
        sub: '',
    },
    {
        id: 41,
        name: 'Buick',
        title: '',
        sub: '',
    },
    {
        id: 42,
        name: 'Cadillac',
        title: '',
        sub: '',
    },
    {
        id: 43,
        name: 'Cadillac',
        title: '',
        sub: '',
    },
    {
        id: 44,
        name: 'Cadillac',
        title: '',
        sub: '',
    },
    {
        id: 45,
        name: 'Buick',
        title: '',
        sub: '',
    },
    {
        id: 46,
        name: 'Mercedes',
        title: '',
        sub: '',
    },
    {
        id: 47,
        name: 'Others',
        title: '',
        sub: '',
    },
    {
        id: 48,
        name: 'Mercedes',
        title: '',
        sub: '',
    },
    {
        id: 49,
        name: 'Buick',
        title: '',
        sub: '',
    },
    {
        id: 50,
        name: 'Cadillac',
        title: '',
        sub: '',
    },
    {
        id: 51,
        name: 'Cadillac',
        title: '',
        sub: '',
    },
    {
        id: 52,
        name: 'Mercedes',
        title: '',
        sub: '',
    },
    {
        id: 53,
        name: 'Mercedes',
        title: '',
        sub: '',
    },
]

categoriesInfo.forEach((car, index) => {
    car.img = `https://dk-car-app.s3.eu-central-1.amazonaws.com/${index+1}/DK+Cars+${index+1}-${2}.jpg`;
});

export default categoriesInfo